framework:
    mailer:
        dsn: '%env(MAILER_DSN)%'
        envelope:
            sender: 'noreply@mrezasolidarnosti.org'
        headers:
            From: 'Mreža Solidarnosti <noreply@mrezasolidarnosti.org>'