---
- name: Create backup directory
  ansible.builtin.file:
    path: "{{ backup_dir }}"
    state: directory
    mode: "0755"
    owner: root
    group: root
  tags: [backup]

- name: Add backup cron job
  ansible.builtin.cron:
    name: "Database backup"
    hour: "3"
    minute: "0"
    job: "mysqldump -u {{ mysql_user }} -p'{{ mysql_password }}' {{ mysql_database }} > {{ backup_dir }}/solidarity_$(date +\\%Y\\%m\\%d).sql"
  tags: [backup]
