---
- name: Deploy tor-blocking.conf for Nginx Tor exit node blocking
  ansible.builtin.copy:
    src: files/etc/nginx/conf.d/tor-blocking.conf
    dest: /etc/nginx/conf.d/tor-blocking.conf
    owner: root
    group: root
    mode: "0644"
  notify: Reload Nginx
  tags: [nginx, tor]
  when: enable_tor_blocking | bool

- name: Ensure tor-ips.conf exists (do not overwrite)
  ansible.builtin.file:
    path: /etc/nginx/snippets/tor-ips.conf
    state: touch
    owner: root
    group: root
    mode: "0644"
  tags: [nginx, tor]
  when: enable_tor_blocking | bool

- name: Deploy update-tor-blocklist.sh script
  ansible.builtin.copy:
    src: files/usr/local/bin/update-tor-blocklist.sh
    dest: /usr/local/bin/update-tor-blocklist.sh
    owner: root
    group: root
    mode: "0755"
  tags: [nginx, tor]
  when: enable_tor_blocking | bool

- name: Deploy cron job for Tor blocklist update
  ansible.builtin.copy:
    src: files/etc/cron.d/update-tor-blocklist
    dest: /etc/cron.d/update-tor-blocklist
    owner: root
    group: root
    mode: "0644"
  tags: [nginx, tor]
  when: enable_tor_blocking | bool

- name: Configure Nginx
  ansible.builtin.template:
    src: templates/etc/nginx/sites-available/solidarity.j2
    dest: /etc/nginx/sites-available/solidarity
    owner: root
    group: root
    mode: "0644"
  notify: Reload Nginx
  tags: [nginx]

- name: Enable Nginx site
  ansible.builtin.file:
    src: /etc/nginx/sites-available/solidarity
    dest: /etc/nginx/sites-enabled/solidarity
    state: link
    owner: root
    group: root
  notify: Reload Nginx
  tags: [nginx]

- name: Remove default Nginx site
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: Reload Nginx
  tags: [nginx]

- name: Set up SSL with Let's Encrypt
  ansible.builtin.command: certbot --nginx -d {{ domain_name }} --non-interactive --agree-tos --email {{ admin_email }}
  when: enable_ssl | bool
  changed_when: true
  tags: [ssl]
