---
- name: Configure Redis
  ansible.builtin.template:
    src: templates/etc/redis/redis.conf.j2
    dest: /etc/redis/redis.conf
    owner: redis
    group: redis
    mode: "0640"
  notify: Restart Redis
  tags: [redis, config]

- name: Ensure Redis service is started and enabled
  ansible.builtin.service:
    name: redis-server
    state: started
    enabled: true
  tags: [redis]
