---
- name: Disable SSH password authentication
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PasswordAuthentication'
    line: 'PasswordAuthentication no'
    state: present
    backrefs: true
  notify: Restart sshd
  become: true
  tags: [ssh, hardening]

- name: Enforce SSH protocol 2
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?Protocol'
    line: 'Protocol 2'
    state: present
    backrefs: true
  notify: Restart sshd
  become: true
  tags: [ssh, hardening]
