---
- name: Deploy Solidarity Network Application
  hosts: all
  become: true
  vars_files:
    - vars.yml
  pre_tasks:
    - name: Print OS information
      ansible.builtin.debug:
        msg: |
          OS: {{ ansible_distribution }} {{ ansible_distribution_version }}
          Kernel: {{ ansible_kernel }}
          Architecture: {{ ansible_architecture }}
          FQDN: {{ ansible_fqdn }}
          Ansible version: {{ ansible_version.full }}
      tags: [always]

    - name: Create Ansible directories for www-data
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: www-data
        group: www-data
        mode: "0755"
        recurse: true
      with_items:
        - /var/www/.ansible
        - /var/www/.ansible/tmp
      tags: [setup]

  tasks:
    - name: Include system tasks
      ansible.builtin.include_tasks:
        file: tasks/system.yml
      tags: [packages, setup]

    - name: Configure UFW firewall (SSH/HTTPS)
      ansible.builtin.include_tasks:
        file: tasks/ufw.yml
      tags: [firewall]

    - name: SSH hardening
      ansible.builtin.include_tasks:
        file: tasks/ssh_hardening.yml
      tags: [ssh, hardening]

    - name: Include PHP tasks
      ansible.builtin.include_tasks:
        file: tasks/php.yml
      tags: [php]

    - name: Include Redis tasks
      ansible.builtin.include_tasks:
        file: tasks/redis.yml
      tags: [redis]

    - name: Include Nginx tasks
      ansible.builtin.include_tasks:
        file: tasks/nginx.yml
      tags: [nginx, ssl, tor]

    - name: Application setup tasks
      ansible.builtin.include_tasks:
        file: tasks/app_setup.yml
      tags: [deploy]

    - name: Database tasks
      ansible.builtin.include_tasks:
        file: tasks/db.yml
      tags: [deploy, database]

    - name: Cache tasks
      ansible.builtin.include_tasks:
        file: tasks/cache.yml
      tags: [deploy, cache]

    - name: Backup tasks
      ansible.builtin.include_tasks:
        file: tasks/backup.yml
      tags: [backup]


  roles:
    - role: geerlingguy.mysql
      tags: [mysql]
    - role: geerlingguy.swap
      tags: [swap]

  handlers:
    - name: Restart PHP-FPM
      ansible.builtin.service:
        name: php8.3-fpm
        state: restarted

    - name: Restart Redis
      ansible.builtin.service:
        name: redis-server
        state: restarted

    - name: Reload Nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded

    - name: Restart sshd
      ansible.builtin.service:
        name: ssh
        state: restarted
      become: true
